### PR TITLE
Merge Release/v0.7.6 into master

### PR DESCRIPTION
**Pull request by minsulee2**
0.7.6. is now ready to merge into master!

Includes:
- Version up(v0.7.6)
- _createApp integration with /apps config
- Support blockchain data preservation
- Do function sanitization logic in setFunction()
- Add more servered characters (<, >, ', ", `, ' ') and test cases
- Update scripts
- Add sanitization logic (isValidRuleTree(), isValidRuleConfig()) for rule tree
- Add p2p unittest cases
- Fix minor bugs

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by liayoo** [comment]
LGTM! Could you add the following to the release note? Thanks!
- _createApp integration with /apps config
- Support blockchain data preservation

**Review by liayoo — APPROVED** [review]

**Comment by minsulee2** [comment]
> LGTM! Could you add the following to the release note? Thanks!
> 
> * _createApp integration with /apps config
> * Support blockchain data preservation

@liayoo Thanks! updated in this PR as well!

**Comment by minsulee2** [comment]
Thanks for the reviews! am gonna release right after merging this PR.

**Pull request merged**
