### PR TITLE
change command in readme.md

### PR DESCRIPTION
**Pull request by gmlee329**
change command 'sh' for 'setup_tracker_gcp.sh' to 'source'  in 'readme.md' to be in ../ain-blockchain after setting everything up.
#87

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by platfowner** [comment]
@gmlee329  could you also update `sh setup_node_gcp.sh` part?

**Comment by gmlee329** [comment]
> @gmlee329 could you also update `sh setup_node_gcp.sh` part?

**Comment by gmlee329** [comment]
@platfowner I've updated that part!

**Comment by platfowner** [comment]
@gmlee329 thanks!

**Pull request merged**
