### PR TITLE
Feature/logger updates

### PR DESCRIPTION
**Pull request by minsulee2**
- if(DEBUG) statements are not necessary anymore
- Logs are colorized
- winston-util.js is added to easily deal with logging options

### CODE REVIEW

**Comment by liayoo** [comment]
Nice to see these improvements! Could you remove the `if (DEBUG) {...}`'s in ./server/index.js as well?

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by minsulee2** [comment]
@liayoo I missed them! just removed them all! Thanks for the review!

**Comment by minsulee2** [comment]
I am merging it just right after leaving this comment! Thanks for the reviews!

**Pull request merged**
