### PR TITLE
Support incremental deploy w/ code updates

### PR DESCRIPTION
**Pull request by liayoo**
Added options to deploy & start node scripts that allow full control of code & data
- --keep-code (was previously automatically determined by --restart or --reset)
- --keep-data (was previously --restart, which also controlled code deployment)

### CODE REVIEW

**Comment by platfowner** [comment]
question: how many combinations were actually tested on the cloud? substantial cases we have are..
-> genesis case: 4 = 2 (keep code or not) * 2 (keep data or not) 
-> incremental case: 8 = 2 (canary or not) * 2 (keep code or not) * 2 (keep data or not)

**Review by platfowner — APPROVED** [review]
LGTM with some questions.
Thanks for the fast progress!

**Comment by liayoo** [comment]
> question: how many combinations were actually tested on the cloud? substantial cases we have are.. -> genesis case: 4 = 2 (keep code or not) * 2 (keep data or not) -> incremental case: 8 = 2 (canary or not) * 2 (keep code or not) * 2 (keep data or not)

These are the cases I've tested so far:
- Genesis: 1 (--keep-code=false, --keep-data=false)
- Incremental: 4 (all 4 cases without canary)

**Comment by liayoo** [comment]
Finished testing all 12 cases. Fyi, I was trying to use a GCP instance for deploying like I've been doing in sandbox, but it kept getting stuck in the account injection stage.. Let me merge this PR though since the scripts are working in local.

**Comment by platfowner** [comment]
> Finished testing all 12 cases. Fyi, I was trying to use a GCP instance for deploying like I've been doing in sandbox, but it kept getting stuck in the account injection stage.. Let me merge this PR though since the scripts are working in local. cc: @platfowner

thanks for the hard work!
you mean a GCP instance as a client machine?

**Comment by liayoo** [comment]
> > Finished testing all 12 cases. Fyi, I was trying to use a GCP instance for deploying like I've been doing in sandbox, but it kept getting stuck in the account injection stage.. Let me merge this PR though since the scripts are working in local. cc: @platfowner
> 
> thanks for the hard work! you mean a GCP instance as a client machine?

Thanks! And yes, I've been using an e2-micro instance named 'blockchain-deployer' for the sandbox and created a similar instance in staging~

**Pull request merged**
