### PR TITLE
Allow function IDs (auth.fid) in owner config

### PR DESCRIPTION
**Pull request by platfowner**
Change summary:
- Allow function IDs (auth.fid) in owner config
- Add _setOwnerConfig native function for testing
- Rename execGasAmount -> extraGasAmount

Related issue: https://github.com/ainblockchain/ain-blockchain/issues/406

### CODE REVIEW

**Comment by liayoo** [comment]
This made me realize that we currently do not have a check for owner values (e.g. check if the object's key is either an address or a string starting with 'fid:')! Should we maybe add a todo for that?

**Review by liayoo — APPROVED** [review]
LGTM with a comment. Thanks!

**Comment by platfowner** [comment]
> This made me realize that we currently do not have a check for owner values (e.g. check if the object's key is either an address or a string starting with 'fid:')! Should we maybe add a todo for that?

Actually, we have a todo for the owner config value sanitization: https://github.com/ainblockchain/ain-blockchain/blob/master/db/index.js#L749 

I think the issue can be covered when we add the sanitization logic.
Thanks!

**Comment by platfowner** [comment]
Thanks for the review. Now being merged..

**Pull request merged**
