### PR TITLE
Allow undefined gas_price.

### PR DESCRIPTION
**Pull request by liayoo**
- Allow transactions without the 'gas_price' field
- Use default gas price of 1 microain

### CODE REVIEW

**Review by cshcomcom — APPROVED** [review]
LGTM! Thanks for the quick fix!!

**Comment by platfowner** [comment]
As discussed offline, please consider the followings: @liayoo 
- Allow undefined gas_price (backward compatibility) 
- Interpret default value = 0 (to make things simple) 
- Use ENABLE_GAS_FEE_WORKAROUND to allow zero gas price

**Comment by liayoo** [comment]
> As discussed offline, please consider the followings: @liayoo
> 
> * Allow undefined gas_price (backward compatibility)
> * Interpret default value = 0 (to make things simple)
> * Use ENABLE_GAS_FEE_WORKAROUND to allow zero gas price

Updated to reflect our latest discussion. PTAL!

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

Could you merge it quickly?

**Pull request merged**
