### PR TITLE
Bugfix/proof updates

### PR DESCRIPTION
**Pull request by minsulee2**

### CODE REVIEW

**Review by platfowner — COMMENTED** [review]
Nice catch!
Could you also add a test case for makeCopyOfStateTree()?
e.g. when a state tree is copied the proof hash of the root node is also copied.

**Comment by minsulee2** [comment]
PTAL. Not only have I updated makeCopyOfStateTree(), but I also updated setting null when deleting stateTree!!

**Comment by minsulee2** [comment]
PTAL, I am waiting for this :) and conflict resolved!

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by minsulee2** [comment]
Thanks for the review! I will merge it as soon as leaving this comment!

**Pull request merged**
