### PR TITLE
Feature/service integrity

### PR DESCRIPTION
**Pull request by liayoo**
- Improved service integrity & reusability by consistently using the app's admin for permission checking
- Removed service account admins
- Replaced _openEscrow native function with setting value at escrow account's config path
- Updated tests & tool scripts

### CODE REVIEW

**Comment by platfowner** [comment]
@liayoo Could you sync the branch?

**Comment by liayoo** [comment]
> @liayoo Could you sync the branch?

Done! ✅

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by liayoo** [comment]
Thanks for the quick review! 👍

**Pull request merged**
