### PR TITLE
Add --skip-kill, --kill-only options to deploy scripts

### PR DESCRIPTION
**Pull request by liayoo**
Added `--skip-kill` and `--kill-only` options to the deploy scripts so that we can kill all processes first and then deploy when we need to use multiple deploy scripts for a chain.
For example,
```
bash deploy_blockchain_genesis_gcp.sh sandbox liayoo 0 --kill-only
bash deploy_blockchain_sandbox_gcp.sh liayoo 7 29 --kill-only
bash deploy_blockchain_genesis_gcp.sh sandbox liayoo 0 --skip-kill
bash deploy_blockchain_sandbox_gcp.sh liayoo 7 29 --skip-kill
```

### CODE REVIEW

**Review by minsulee2 — APPROVED** [review]
Oh, I love it! I usually comment out them tho haha

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by liayoo** [comment]
> Oh, I love it! I usually comment out them tho haha

Yeah, me too! Wanted to avoid that :)

**Comment by liayoo** [comment]
Thanks for the quick review!

**Pull request merged**
