### PR TITLE
Use 2 for both chain and network ID

### PR DESCRIPTION
**Pull request by minsulee2**
Updates:
- Use 2 for chain ID!
- Rebuild genesis_block.json.gz for testnet-dev

### CODE REVIEW

**Comment by liayoo** [comment]
Could you revert the change for the testnet-prod genesis block?

**Comment by platfowner** [comment]
> Could you revert the change for the testnet-prod genesis block?

Right, the file shouldn't be changed, could you check why? @minsulee2

**Comment by platfowner** [comment]
> > Could you revert the change for the testnet-prod genesis block?
> 
> Right, the file shouldn't be changed, could you check why? @minsulee2

Ah, just realized that the genesis block generation requires owner private keys. So for testnet-prod and mainnet-prod, I think you can ignore the errors and simply revert related changes from this PR. @minsulee2  cc: @liayoo

**Comment by minsulee2** [comment]
@platfowner @liayoo I found out that the gz file in testnet-prod was removed when running the script. Thanks for the explain! Mystery resolved!! PTAL!

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

Could you also update the developer's guide?
https://docs.ainetwork.ai/developer-guide/ai-network-design/network-id-and-chain-id

**Comment by minsulee2** [comment]
Thanks for the fast review! Merging now and move on to developer's guide!

**Pull request merged**
