### PR TITLE
Release v0.3.1

### PR DESCRIPTION
**Pull request by minsulee2**

### CODE REVIEW

**Comment by platfowner** [comment]
@minsulee2  Could you increase the version in package.json? As mentioned by @liayoo in another thread, client/protocol_versions.json needs to be updated as well.

**Comment by minsulee2** [comment]
@platfowner I made PR for version up! please take a look #119 :)

**Comment by minsulee2** [comment]
PTAL. The version has been set to v0.3.1

**Comment by minsulee2** [comment]
PTAL again! version up updated!

**Review by liayoo — APPROVED** [review]
LGTM, thanks! 🚀

**Comment by minsulee2** [comment]
Thanks for the review! I am merging it now!

**Pull request merged**
