### PR TITLE
Change bandwidth_budget_per_block limit to 1000000

### PR DESCRIPTION
**Pull request by cshcomcom**

### CODE REVIEW

**Comment by liayoo** [comment]
Could you update the genesis block as well? (Running `bash rebuild_genesis_blocks.sh` will create a new block)

**Comment by cshcomcom** [comment]
Thanks! Done! I also changed sandbox's genesis_block file. @liayoo

**Review by liayoo — APPROVED** [review]
LGTM, thanks!

**Comment by cshcomcom** [comment]
Thanks for the quick review! Now merging

**Pull request merged**
