### PR TITLE
Include updates in develop branch

### PR DESCRIPTION
**Pull request by minsulee2**
Merge develop into release/v0.9.2
Include recent updates including #628

### CODE REVIEW

**Comment by platfowner** [comment]
Please wait for https://github.com/ainblockchain/ain-blockchain/pull/628 to be merged.

**Comment by minsulee2** [comment]
@platfowner Oh, right. I am waiting for it!

**Review by liayoo — APPROVED** [review]
LGTM, thanks!

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Pull request merged**
