### PR TITLE
Update ain-util

### PR DESCRIPTION
**Pull request by minsulee2**

### CODE REVIEW

**Comment by minsulee2** [comment]
This is regarding on issue #8

**Comment by liayoo** [comment]
@minsulee2 The lodash security fix pr has just been merged but it hasn't been released yet, and v1.1.4 doesn't include the changes. Could you postpone the merge until we release an updated version of ain-util?

**Comment by minsulee2** [comment]
@liayoo Yeah I checked the v1.1.4 is under construction! But, keep it in mind that this kinda fix will show up over and over and over.. That's why I opened the issue #8 and keep tracking vulnerability issues. Thanks!

**Comment by minsulee2** [comment]
ain-utils v1.1.5 has just been updated. I will merge it this PR and address this in the issue #8 .

**Pull request merged**
