### PR TITLE
Add cpu_status info to grafana.json

### PR DESCRIPTION
**Pull request by cshcomcom**
## Description
- Add cpu_status:usage to grafana.json

### CODE REVIEW

**Review by platfowner — APPROVED** [review]
LGTM

BTW I think the cpu values can be converted to more human-friendly values (e.g. usage percent) by the blockchain node. (Maybe in the next release)

**Comment by cshcomcom** [comment]
Thanks for the quick review! How can we get usage percent from elapsedTimeMs!?

**Comment by cshcomcom** [comment]
Now merging

**Comment by platfowner** [comment]
> Thanks for the quick review! How can we get usage percent from elapsedTimeMs!?

elapsedTimeMs is just a reference: https://github.com/ainblockchain/ain-blockchain/blob/master/p2p/server.js#L155

We can get whatever we want by manipulating given info?

**Comment by platfowner** [comment]
> > Thanks for the quick review! How can we get usage percent from elapsedTimeMs!?
> 
> elapsedTimeMs is just a reference: https://github.com/ainblockchain/ain-blockchain/blob/master/p2p/server.js#L155
> 
> We can get whatever we want by manipulating given info?

ref: https://stackoverflow.com/questions/9565912/convert-the-output-of-os-cpus-in-node-js-to-percentage

**Pull request merged**
