### PR TITLE
Remove redundant code

### PR DESCRIPTION
**Pull request by platfowner**

### CODE REVIEW

**Comment by liayoo** [comment]
Could you help me understand why this is redundant and similar code in [functions.test.js](https://github.com/ainblockchain/ain-blockchain/blob/develop/unittest/functions.test.js#L106) is not..?

**Comment by platfowner** [comment]
@liayoo Ah, this mocking code catches network requests in unit tests but in integration tests it cannot as the servers run as standalone jobs.

**Review by minsulee2 — APPROVED** [review]
LGTM! Good to see tidy up!!

**Review by liayoo — APPROVED** [review]
LGTM. Thanks for the explanation!

**Pull request merged**
